# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hack4RiOMar Jupyter Notebook
author: The Pangeo and FAIR2Adapt Communities
logo: https://avatars.githubusercontent.com/u/23299451?s=400&u=5a8c93b430a51e03c29eaac8c5ff62cb10063c22&v=4

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: Hack4RiOMar.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/FAIR2Adapt/Hack4RiOMAR  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton
